# Generated by Django 2.1 on 2018-09-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ArcadePrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('success_rate', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlueprintInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryArcadeTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('tile_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'friend'), (2, 'pending'), (3, 'blocked')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'background'), (2, 'badge'), (3, 'blueprint'), (4, 'item'), (5, 'loop'), (6, 'masterpiece'), (7, 'module'), (8, 'movie'), (9, 'skin'), (10, 'sticker')])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('easy_replies', models.ManyToManyField(related_name='_messagebody_easy_replies_+', to='mln.MessageBody')),
            ],
            options={
                'verbose_name_plural': 'Message bodies',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.PositiveSmallIntegerField()),
                ('pos_y', models.PositiveSmallIntegerField()),
                ('last_harvest_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('clicks_since_last_harvest', models.PositiveSmallIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('is_setup', models.BooleanField(default=False)),
                ('item', models.ForeignKey(limit_choices_to={'type': 7}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleExecutionCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('module_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_executable', models.BooleanField()),
                ('is_setupable', models.BooleanField()),
                ('href_editor', models.CharField(blank=True, max_length=256, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSaveConcertArcade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_played', models.BooleanField()),
                ('background_skin', models.PositiveSmallIntegerField()),
                ('arrowset_skin', models.PositiveSmallIntegerField()),
                ('arrows', models.BigIntegerField()),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_concert_arcade', to='mln.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleSaveDeliveryArcade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_played', models.BooleanField()),
                ('timer', models.PositiveSmallIntegerField()),
                ('house_0_x', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('house_0_y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('house_1_x', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('house_1_y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('house_2_x', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('house_2_y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_x', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_delivery_arcade', to='mln.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleSaveDestructoidArcade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_played', models.BooleanField()),
                ('energy_used', models.PositiveSmallIntegerField()),
                ('character_skin', models.PositiveSmallIntegerField(choices=[(1, 'man'), (2, 'lizard')])),
                ('block_skin', models.PositiveSmallIntegerField(choices=[(1, 'pbrick'), (2, 'skull')])),
                ('background_skin', models.PositiveSmallIntegerField()),
                ('top', models.BigIntegerField()),
                ('middle', models.BigIntegerField()),
                ('bottom', models.BigIntegerField()),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_destructoid_arcade', to='mln.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleSaveGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.Color')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_generic', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSaveHopArcade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_played', models.BooleanField()),
                ('top', models.BigIntegerField()),
                ('middle', models.BigIntegerField()),
                ('bottom', models.BigIntegerField()),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_hop_arcade', to='mln.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleSaveNetworkerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_networker_text', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSaveRocketGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.PositiveSmallIntegerField(choices=[(1, 'space'), (2, 'punk'), (3, 'mars')])),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_rocket_game', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSaveSoundtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_0_0_pan', models.SmallIntegerField()),
                ('sound_0_1_pan', models.SmallIntegerField()),
                ('sound_0_2_pan', models.SmallIntegerField()),
                ('sound_0_3_pan', models.SmallIntegerField()),
                ('sound_1_0_pan', models.SmallIntegerField()),
                ('sound_1_1_pan', models.SmallIntegerField()),
                ('sound_1_2_pan', models.SmallIntegerField()),
                ('sound_1_3_pan', models.SmallIntegerField()),
                ('sound_2_0_pan', models.SmallIntegerField()),
                ('sound_2_1_pan', models.SmallIntegerField()),
                ('sound_2_2_pan', models.SmallIntegerField()),
                ('sound_2_3_pan', models.SmallIntegerField()),
                ('sound_3_0_pan', models.SmallIntegerField()),
                ('sound_3_1_pan', models.SmallIntegerField()),
                ('sound_3_2_pan', models.SmallIntegerField()),
                ('sound_3_3_pan', models.SmallIntegerField()),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_soundtrack', to='mln.Module')),
                ('sound_0_0', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_0_1', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_0_2', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_0_3', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_1_0', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_1_1', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_1_2', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_1_3', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_2_0', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_2_1', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_2_2', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_2_3', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_3_0', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_3_1', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_3_2', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('sound_3_3', models.ForeignKey(blank=True, limit_choices_to={'type': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSaveSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('scale_x', models.SmallIntegerField()),
                ('scale_y', models.SmallIntegerField()),
                ('rotation', models.SmallIntegerField()),
                ('depth', models.SmallIntegerField()),
                ('item', models.ForeignKey(limit_choices_to=models.Q(('type', 1), ('type', 10), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_sticker', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSaveUGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.PositiveIntegerField()),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_ugc', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSetupCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('module_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleSetupFriendShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_friend_share', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSetupGroupPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_0', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('friend_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('friend_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_group_performance', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSetupTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_qty', models.PositiveSmallIntegerField()),
                ('request_qty', models.PositiveSmallIntegerField()),
                ('give_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_trade', to='mln.Module')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSetupTrioPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_0', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('friend_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_trio_performance', to='mln.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleYieldInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_yield', models.PositiveSmallIntegerField()),
                ('yield_per_day', models.PositiveSmallIntegerField()),
                ('clicks_per_yield', models.PositiveSmallIntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
                ('yield_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_networker', models.BooleanField(default=False)),
                ('avatar', models.CharField(default='0#1,6,1,16,5,1,6,13,2,9,2,2,1,1', max_length=64)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('available_votes', models.PositiveSmallIntegerField(default=20)),
                ('last_vote_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_column_color_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('friends', models.ManyToManyField(through='mln.Friendship', to='mln.Profile')),
                ('page_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.Color')),
                ('page_skin', models.ForeignKey(blank=True, limit_choices_to={'type': 9}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.ItemInfo')),
                ('statement_0_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('mandatory', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StartingStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_0_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_1_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_1_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_2_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_2_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_3_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_3_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_4_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_4_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_5_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_5_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulesavegeneric',
            name='skin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ModuleSkin'),
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.MessageBody'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.MessageBody'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystack',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='inventorystack',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_friendships', to='mln.Profile'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_friendships', to='mln.Profile'),
        ),
        migrations.AddField(
            model_name='deliveryarcadetile',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='mln.Module'),
        ),
        migrations.AddField(
            model_name='blueprintrequirement',
            name='blueprint_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='blueprintrequirement',
            name='item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 2), ('type', 4), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='blueprintinfo',
            name='build',
            field=models.OneToOneField(limit_choices_to=models.Q(('type', 2), ('type', 4), ('type', 6), ('type', 7), ('type', 8), ('type', 9), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='blueprintinfo',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mln.Message'),
        ),
        migrations.AddField(
            model_name='arcadeprize',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='arcadeprize',
            name='module_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.Question'),
        ),
    ]
