# Generated by Django 2.1 on 2018-09-27 14:02

from django.db import migrations, models
import django.db.models.deletion
import mln.models.dynamic
import mln.models.dynamic.module_settings
import mln.models.dynamic.module_settings_arcade
import mln.models.static


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintinfo',
            name='build',
            field=models.OneToOneField(limit_choices_to=models.Q(('type', mln.models.static.ItemType(2)), ('type', mln.models.static.ItemType(4)), ('type', mln.models.static.ItemType(6)), ('type', mln.models.static.ItemType(7)), ('type', mln.models.static.ItemType(8)), ('type', mln.models.static.ItemType(9)), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='blueprintrequirement',
            name='item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.ItemType(2)), ('type', mln.models.static.ItemType(4)), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=mln.models.static.EnumField(mln.models.dynamic.FriendshipStatus, default=mln.models.dynamic.FriendshipStatus(2)),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='type',
            field=mln.models.static.EnumField(mln.models.static.ItemType),
        ),
        migrations.AlterField(
            model_name='module',
            name='item',
            field=models.ForeignKey(limit_choices_to={'type': mln.models.static.ItemType(7)}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavedestructoidarcade',
            name='block_skin',
            field=mln.models.static.EnumField(mln.models.module_settings_arcade.DestructoidBlockSkin),
        ),
        migrations.AlterField(
            model_name='modulesavedestructoidarcade',
            name='character_skin',
            field=mln.models.static.EnumField(mln.models.module_settings_arcade.DestructoidCharacterSkin),
        ),
        migrations.AlterField(
            model_name='modulesaverocketgame',
            name='theme',
            field=mln.models.static.EnumField(mln.models.module_settings.RocketGameTheme),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_0',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_3',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_0',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_3',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_0',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_3',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_0',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_3',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(5)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesavesticker',
            name='item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.ItemType(1)), ('type', mln.models.static.ItemType(10)), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='page_skin',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': mln.models.static.ItemType(9)}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.ItemInfo'),
        ),
    ]
