# Generated by Django 2.1 on 2018-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0002_DATA_xml_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_networker',
            field=models.BooleanField(default=False),
        ),
    ]
