# Generated by Django 2.1 on 2018-09-28 08:13

from django.db import migrations
from mln.models import ModuleEditorType
import mln.models

href_types = {
	"download3C08891ADDFAF741ECF73F38FB40B2A3":   ModuleEditorType.CONCERT_I_ARCADE,
	"download124C900AD0613F3B0E8683473AC6B267":   ModuleEditorType.CONCERT_II_ARCADE,
	"download7BBDE1968863AF36A4723D79CEBE817E":   ModuleEditorType.DELIVERY_ARCADE,
	"download6308BE1BFE39A4E7A3ADC4D112807016":   ModuleEditorType.DESTRUCTOID_ARCADE,
	"download65E88EEE1750F1FF25361D8A52651BF1":   ModuleEditorType.DR_INFERNO_ROBOT_SIM,
	"upload94145C71-2215-40F4-BC55-705F8CA24ACA": ModuleEditorType.FACTORY_GENERIC,
	"upload6FE45D31-426C-41DC-96F0-04C16BDAC640": ModuleEditorType.FACTORY_NON_GENERIC,
	"upload5E54C1F7-9D69-4089-A28B-C9A6054C2482": ModuleEditorType.FRIEND_SHARE,
	"download8D2D8E39CFEEF2BE409F2557F48F810C":   ModuleEditorType.FRIENDLY_FELIX_CONCERT,
	"upload6BE2047F-A1E7-46FE-ABE9-CD910C6EF59D": ModuleEditorType.GALLERY_GENERIC,
	"uploadE79A5782-F4CC-4FA6-B71B-5266E2830236": ModuleEditorType.GALLERY_NON_GENERIC,
	"upload5F35F258-650A-46E6-A4F3-07C4823F51EA": ModuleEditorType.GENERIC,
	"uploadBD27CDD3-01AB-4A14-B065-44AD7295987F": ModuleEditorType.GROUP_PERFORMANCE,
	"download16F9FFF4A1719FF27AA4E4BD59ACAC27":   ModuleEditorType.HOP_ARCADE,
	"upload2ADB5931-F7EE-4363-9AFB-EBA8E45C6FB8": ModuleEditorType.LOOP_SHOPPE,
	"uploadC85FF476-57A7-41EE-BA1A-45D259F438A8": ModuleEditorType.NETWORKER_TEXT,
	"upload66F5B629-AEB6-4C04-B56C-BC1BCA22ABF5": ModuleEditorType.NETWORKER_TRADE,
	"uploadD668BCBE-4B58-406B-91C8-3C09AC4216DF": ModuleEditorType.PLASTIC_PELLET_INDUCTOR,
	"upload3B10831D-FEBE-4C44-B964-6D69B49EA1C6": ModuleEditorType.ROCKET_GAME,
	"upload5CD17986-C326-4A56-9094-552F275D5906": ModuleEditorType.SOUNDTRACK,
	"upload617A0D10-FA99-42AA-8B44-6534997F8819": ModuleEditorType.STICKER,
	"upload28814700-1EEA-458C-A494-6C4797739455": ModuleEditorType.STICKER_SHOPPE,
	"uploadB58AC317-A0A2-41C4-8AA7-2086AB69CE9A": ModuleEditorType.TRADE,
	"uploadF10B502A-8D24-43E3-BA33-84C183B5D857": ModuleEditorType.TRIO_PERFORMANCE,
}

def migrate_href(apps, schema_editor):
	ModuleInfo = apps.get_model("mln", "ModuleInfo")
	for info in ModuleInfo.objects.all():
		href = info.href_editor
		if href is None:
			info.editor_type = None
		else:
			href = href[href.rindex("/")+1:href.rindex(".")]
			info.editor_type = href_types[href]
		info.save()

class Migration(migrations.Migration):
	dependencies = [
		('mln', '0002_enumfield'),
	]

	operations = [
		migrations.AddField(
			model_name='moduleinfo',
			name='editor_type',
			field=mln.models.utils.EnumField(mln.models.ModuleEditorType, default=ModuleEditorType.GENERIC, null=True, blank=True),
			preserve_default=False,
		),
		migrations.RunPython(migrate_href),
		migrations.RemoveField(
			model_name='moduleinfo',
			name='href_editor',
		),
	]
