# Generated by Django 2.1 on 2018-10-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0003_moduleinfo_editor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesaveconcertarcade',
            name='arrows',
        ),
        migrations.AddField(
            model_name='modulesaveconcertarcade',
            name='arrows_down',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulesaveconcertarcade',
            name='arrows_left',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulesaveconcertarcade',
            name='arrows_right',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulesaveconcertarcade',
            name='arrows_up',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
