# Generated by Django 2.1 on 2018-08-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0003_profile_is_networker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='statement_0_a',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_0_q',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_1_a',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_1_q',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_2_a',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_2_q',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_3_a',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_3_q',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_4_a',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_4_q',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_5_a',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statement_5_q',
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_0_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_0_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_1_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_1_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_2_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_2_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_3_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_3_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_4_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_4_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_5_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement_5_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question'),
        ),
    ]
