# Generated by Django 2.1 on 2018-09-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0004_profile_statements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.MessageBody'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='page_column_color_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
