# Generated by Django 2.1 on 2018-11-01 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mln.models

class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0005_hop_arcade_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryarcadetile',
            name='x',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='deliveryarcadetile',
            name='y',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='pos_x',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='pos_y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='moduleexecutioncost',
            name='item',
            field=models.ForeignKey(limit_choices_to={'type': mln.models.ItemType(4)}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='moduleinfo',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_info', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='modulesaveconcertarcade',
            name='arrowset_skin',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='modulesaveconcertarcade',
            name='background_skin',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='house_0_x',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='house_0_y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='house_1_x',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='house_1_y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='house_2_x',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='house_2_y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='start_x',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavedeliveryarcade',
            name='start_y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_0_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_1_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_2_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_0_3_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_0_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_1_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_2_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_1_3_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_0_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_1_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_2_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_2_3_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_0_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_1_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_2_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesavesoundtrack',
            name='sound_3_3_pan',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modulesetupcost',
            name='item',
            field=models.ForeignKey(limit_choices_to={'type': mln.models.ItemType(4)}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='moduleyieldinfo',
            name='yield_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.ItemType(3)), ('type', mln.models.ItemType(4)), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='page_column_color_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
