# Generated by Django 2.1 on 2019-01-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0007_messagebody_subject_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkerMessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkerMessageTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networker', models.CharField(max_length=64)),
                ('trigger', models.TextField()),
                ('source', models.TextField()),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.MessageBody')),
            ],
        ),
        migrations.AddField(
            model_name='networkermessageattachment',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mln.NetworkerMessageTrigger'),
        ),
    ]
