# Generated by Django 2.1 on 2019-01-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0008_networker_message_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkermessagetrigger',
            name='networker',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='networkermessagetrigger',
            name='trigger',
            field=models.TextField(blank=True, null=True),
        ),
    ]
