# Generated by Django 2.1 on 2019-02-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0010_networker_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkerfriendshipcondition',
            old_name='success_source',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='networkerfriendshipcondition',
            name='failure_source',
        ),
        migrations.AlterField(
            model_name='networkerfriendshipcondition',
            name='condition',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='networkerfriendshipcondition',
            name='failure_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.MessageBody'),
        ),
        migrations.AlterField(
            model_name='networkerfriendshipcondition',
            name='success_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.MessageBody'),
        ),
    ]
