# Generated by Django 2.1 on 2019-02-04 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migrate_statements(apps, schema_editor):
	AboutMe = apps.get_model("mln", "AboutMe")
	Profile = apps.get_model("mln", "Profile")

	for profile in Profile.objects.filter(statement_0_question__isnull=False):
		q_0 = profile.statement_0_question
		a_0 = profile.statement_0_answer
		q_1 = profile.statement_1_question
		a_1 = profile.statement_1_answer
		q_2 = profile.statement_2_question
		a_2 = profile.statement_2_answer
		q_3 = profile.statement_3_question
		a_3 = profile.statement_3_answer
		q_4 = profile.statement_4_question
		a_4 = profile.statement_4_answer
		q_5 = profile.statement_5_question
		a_5 = profile.statement_5_answer
		AboutMe.objects.create(user=profile.user, question_0=q_0, answer_0=a_0, question_1=q_1, answer_1=a_1, question_2=q_2, answer_2=a_2, question_3=q_3, answer_3=a_3, question_4=q_4, answer_4=a_4, question_5=q_5, answer_5=a_5)

class Migration(migrations.Migration):
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('mln', '0011_friendship_simplify'),
	]

	operations = [
		migrations.CreateModel(
			name='AboutMe',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('answer_0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer')),
				('answer_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer')),
				('answer_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer')),
				('answer_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer')),
				('answer_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer')),
				('answer_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Answer')),
				('question_0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question')),
				('question_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question')),
				('question_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question')),
				('question_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question')),
				('question_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question')),
				('question_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mln.Question')),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to=settings.AUTH_USER_MODEL)),
			],
		),
		migrations.RunPython(migrate_statements),
		migrations.RemoveField(
			model_name='profile',
			name='statement_0_answer',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_0_question',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_1_answer',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_1_question',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_2_answer',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_2_question',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_3_answer',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_3_question',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_4_answer',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_4_question',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_5_answer',
		),
		migrations.RemoveField(
			model_name='profile',
			name='statement_5_question',
		),
	]
