# Generated by Django 2.1 on 2019-04-10 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models
import django.db.models.deletion

class Migration(migrations.Migration):

	dependencies = [
		('mln', '0014_networker_friendship'),
	]

	operations = [
			migrations.RemoveField(
			model_name='profile',
			name='friends',
		),
		migrations.RenameField(
			model_name='friendship',
			old_name='from_profile',
			new_name='from_user',
		),
		migrations.RenameField(
			model_name='friendship',
			old_name='to_profile',
			new_name='to_user',
		),
		migrations.AlterField(
			model_name='friendship',
			name='from_user',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_friendships', to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterField(
			model_name='friendship',
			name='to_user',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_friendships', to=settings.AUTH_USER_MODEL),
		),
	]
