# Generated by Django 2.1 on 2019-04-14 11:48

from django.db import migrations, models
import django.db.models.deletion
import mln.models.static

def migrate_networker_pics(apps, schema_editor):
	Module = apps.get_model("mln", "Module")
	MSNP = apps.get_model("mln", "ModuleSaveNetworkerPic")
	for module in Module.objects.filter(item__module_info__editor_type=mln.models.static.ModuleEditorType.NETWORKER_PIC):
		for sticker in module.save_sticker.all():
			MSNP.objects.create(module=module, picture=sticker.item)
			break
		module.save_sticker.all().delete()

class Migration(migrations.Migration):
	dependencies = [
		('mln', '0015_friendship'),
	]

	operations = [
		migrations.CreateModel(
			name='ModuleSaveNetworkerPic',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_networker_pic', to='mln.Module')),
				('picture', models.ForeignKey(limit_choices_to={'type': mln.models.static.ItemType(10)}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo')),
			],
		),
		migrations.RunPython(migrate_networker_pics),
	]
