# Generated by Django 2.1 on 2019-04-17 13:17

from django.db import migrations
import mln.models

class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0016_modulesavenetworkerpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=mln.models.EnumField(mln.models.FriendshipStatus),
        ),
    ]
