# Generated by Django 2.2 on 2019-04-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0017_friendship_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleinfo',
            name='is_setupable',
        ),
    ]
