# Generated by Django 2.2 on 2019-04-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0018_remove_moduleinfo_is_setupable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startingstack',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.ItemInfo'),
        ),
        migrations.AddConstraint(
            model_name='arcadeprize',
            constraint=models.UniqueConstraint(fields=('module_item', 'item'), name='unique_module_item_item'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('message', 'item'), name='unique_message_item'),
        ),
        migrations.AddConstraint(
            model_name='blueprintrequirement',
            constraint=models.UniqueConstraint(fields=('blueprint_item', 'item'), name='unique_blueprint_item_item'),
        ),
        migrations.AddConstraint(
            model_name='inventorystack',
            constraint=models.UniqueConstraint(fields=('owner', 'item'), name='unique_owner_item'),
        ),
        migrations.AddConstraint(
            model_name='iteminfo',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_type'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('owner', 'pos_x', 'pos_y'), name='unique_owner_pos'),
        ),
        migrations.AddConstraint(
            model_name='moduleexecutioncost',
            constraint=models.UniqueConstraint(fields=('module_item', 'item'), name='unique_module_item_item'),
        ),
        migrations.AddConstraint(
            model_name='modulesetupcost',
            constraint=models.UniqueConstraint(fields=('module_item', 'item'), name='unique_module_item_item'),
        ),
        migrations.AddConstraint(
            model_name='networkermessageattachment',
            constraint=models.UniqueConstraint(fields=('trigger', 'item'), name='unique_trigger_item'),
        ),
    ]
