# Generated by Django 2.2 on 2019-12-24 11:58

from django.db import migrations, models
import django.db.models.deletion

def create_legacy_category(apps, schema_editor):
	MessageBodyCategory = apps.get_model("mln", "MessageBodyCategory")
	MessageBodyCategory.objects.create(id=1, name="LEGACY", hidden=False, background_color=0, button_color=0, text_color=0)

class Migration(migrations.Migration):

	dependencies = [
		('mln', '0020_networkerpagesource'),
	]

	operations = [
		migrations.CreateModel(
			name='MessageBodyCategory',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=32)),
				('hidden', models.BooleanField()),
				('background_color', models.IntegerField()),
				('button_color', models.IntegerField()),
				('text_color', models.IntegerField()),
			],
		),
		migrations.RunPython(create_legacy_category),
		migrations.AddField(
			model_name='messagebody',
			name='category',
			field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.MessageBodyCategory'),
			preserve_default=False,
		),
	]
