# Generated by Django 3.2.7 on 2021-09-20 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_NMTs(apps, schema_editor): 
	# Create an NMT for each NT
	NetworkerMessageTrigger = apps.get_model("mln", "NetworkerMessageTrigger")
	NetworkerTrigger = apps.get_model("mln", "NetworkerTrigger")
	for trigger in NetworkerTrigger.objects.all():
		NetworkerMessageTrigger.objects.create(networkertrigger_ptr=trigger)

class Migration(migrations.Migration):
	dependencies = [
		('mln', '0022_rename_constraints'),
	]

	operations = [
		# 1. Rename NetworkerMessageTrigger (NMT) to NetworkerTrigger (NT)
		# 2. Migrate NT fields: networker_name, networker, response, source
		# 3. Create NMT: message_body, message_attachment
		# 4. Create an NMT for every existing NT

		# Step 1. Rename NMT to NT
		migrations.RenameModel(
			old_name="NetworkerMessageTrigger",
			new_name="NetworkerTrigger",
		),

		# Step 2. Migrate NetworkerTrigger fields
		migrations.RenameField(  # networker -> networker_name
			model_name="networkertrigger",
			old_name="networker",
			new_name="networker_name",
		),
		migrations.RenameField(  # body --> response
			model_name="networkertrigger",
			old_name="body",
			new_name="response"
		),
		migrations.AddField(  # create networker
			model_name="networkertrigger",
			name="networker",
			field=models.ForeignKey(limit_choices_to={'profile__is_networker': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterField(  # make source nullable
			model_name="networkertrigger",
			name="source",
			field=models.TextField(blank=True, null=True),
		),

		# Step 3. Create (new) NetworkerMessageTrigger
		migrations.CreateModel(
			name="NetworkerMessageTrigger",
			fields=[
				("message_body", models.ForeignKey(to="mln.messagebody", related_name="+", on_delete=models.CASCADE, blank=True, null=True)),
				("message_attachment", models.ForeignKey(to="mln.iteminfo", related_name="+", on_delete=models.CASCADE, blank=True, null=True)),
				("networkertrigger_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mln.networkertrigger')),
			]
		),

		# Step 4. Create NetworkerTriggers
		migrations.RunPython(create_NMTs, reverse_code=migrations.RunPython.noop),
	]
