# Generated by Django 3.2.7 on 2021-09-26 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('mln', '0022_rename_constraints'),
	]

	operations = [
		migrations.RenameModel(
			old_name='NetworkerMessageAttachment',
			new_name='NetworkerMessageAttachmentLegacy',
		),
		migrations.RenameModel(
			old_name='NetworkerMessageTrigger',
			new_name='NetworkerMessageTriggerLegacy',
		),
		migrations.CreateModel(
			name='MessageTemplate',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.messagebody')),
			],
		),
		migrations.CreateModel(
			name='MessageTemplateAttachment',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('qty', models.PositiveSmallIntegerField()),
				('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo')),
				('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mln.messagetemplate')),
			],
		),
		migrations.AddConstraint(
			model_name='messagetemplateattachment',
			constraint=models.UniqueConstraint(fields=('template', 'item'), name='messsage_template_attachment_unique_template_item'),
		),
	]
