# Generated by Django 3.2.7 on 2021-09-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0022_rename_constraints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkerMessageAttachment',
            new_name='NetworkerMessageAttachmentDev',
        ),
        migrations.RenameModel(
            old_name='NetworkerMessageTrigger',
            new_name='NetworkerMessageTriggerDev',
        ),
    ]
