# Generated by Django 3.2.7 on 2021-09-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0023_message_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkerReplyTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_model', to='mln.networkermessagetriggerlegacy')),
                ('message_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo')),
                ('message_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.messagebody')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_trigger', to='mln.messagetemplate')),
            ],
        ),
    ]
