# Generated by Django 3.2.7 on 2021-09-26 18:40

from django.db import migrations, models
import django.db.models.deletion

def migrate_nrt(apps, schema_editor):
	# # Migrates all NetworkerMessageTrigger to MessageTemplate + NetworkerReplyTrigger
	NetworkerMessageTrigger = apps.get_model("mln", "NetworkerMessageTriggerLegacy")
	NetworkerMessageAttachment = apps.get_model("mln", "NetworkerMessageAttachmentLegacy")
	MessageTemplate = apps.get_model("mln", "MessageTemplate")
	MessageTemplateAttachment = apps.get_model("mln", "MessageTemplateAttachment")
	NetworkerReplyTrigger = apps.get_model("mln", "NetworkerReplyTrigger")

	for legacy_trigger in NetworkerMessageTrigger.objects.all():
		template = MessageTemplate.objects.create(body=legacy_trigger.body)
		for attachment in legacy_trigger.attachments.all():
			new_attachment = template.attachments.create(item=attachment.item, qty=attachment.qty)
			attachment.updated = new_attachment
			attachment.save()
		trigger = NetworkerReplyTrigger.objects.create(template=template)
		legacy_trigger.updated = trigger
		legacy_trigger.save()

class Migration(migrations.Migration):

	dependencies = [
		('mln', '0023_message_template'),
	]

	operations = [
		migrations.CreateModel(
			name='NetworkerReplyTrigger',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('message_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo')),
				('message_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.messagebody')),
				('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_trigger', to='mln.messagetemplate')),
			],
		),
		migrations.AddField(
		    model_name='networkermessageattachmentlegacy',
		    name='updated',
		    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy', to='mln.messagetemplateattachment'),
		),
		migrations.AddField(
		    model_name='networkermessagetriggerlegacy',
		    name='updated',
		    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy', to='mln.networkerreplytrigger'),
		),
		migrations.RunPython(migrate_nrt, reverse_code=migrations.RunPython.noop),
	]
