# Generated by Django 3.2.7 on 2021-09-10 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mln', '0023_rename_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkerTrigger',
            fields=[
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trigger', serialize=False, to='mln.messagebody')),
                ('networker', models.ForeignKey(limit_choices_to={'profile__is_networker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='NetworkerMessageAttachmentDev',
            new_name='NetworkerMessageAttachment',
        ),
        migrations.AlterField(
            model_name='networkermessageattachment',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mln.networkertrigger'),
        ),
        migrations.CreateModel(
            name='NetworkerMessageTrigger',
            fields=[
                ('networkertrigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mln.networkertrigger')),
                ('message_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo')),
                ('message_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.messagebody')),
            ],
            bases=('mln.networkertrigger',),
        ),
    ]
