# Generated by Django 3.2.7 on 2021-10-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0024_networker_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkermessagetriggerlegacy',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy', to='mln.networkerreply'),
        ),
    ]
