# Generated by Django 3.2.7 on 2021-09-09 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mln', '0025_alter_message_recipient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkerFriendshipCondition',
            new_name='NetworkerFriendshipConditionDev',
        ),
        migrations.RenameModel(
            old_name='NetworkerFriendshipConditionSource',
            new_name='NetworkerFriendshipConditionSourceDev',
        ),
    ]
