# Generated by Django 3.2.7 on 2021-10-06 19:17

from django.db import migrations
import mln.models.static


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0025_alter_networkermessagetriggerlegacy_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebody',
            name='type',
            field=mln.models.static.EnumField(mln.models.static.MessageBodyType, null=True, blank=True),
        ),
    ]
