# Generated by Django 3.2.7 on 2021-09-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mln', '0026_auto_20210909_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkermessagetrigger',
            name='networker',
            field=models.OneToOneField(default=None, limit_choices_to={'profile__is_networker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='networkermessagetrigger',
            name='response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='mln.message'),
        ),
        migrations.CreateModel(
            name='NetworkerFriendTrigger',
            fields=[
                ('response', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='mln.message')),
                ('accept', models.BooleanField(default=True)),
                ('networker', models.OneToOneField(default=None, limit_choices_to={'profile__is_networker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('required_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
