# Generated by Django 3.2.7 on 2021-09-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0027_auto_20210909_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkerfriendtrigger',
            name='required_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo'),
        ),
    ]
