# Generated by Django 3.2.7 on 2022-01-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0027_rename_moduleyieldinfo_moduleharvestyield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='is_setup',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
