# Generated by Django 3.2.7 on 2021-09-09 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mln', '0028_alter_networkerfriendtrigger_required_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkerfriendtrigger',
            name='networker',
            field=models.ForeignKey(default=None, limit_choices_to={'profile__is_networker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='networkermessagetrigger',
            name='networker',
            field=models.ForeignKey(default=None, limit_choices_to={'profile__is_networker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
