# Generated by Django 3.2.7 on 2022-06-01 22:25

from django.db import migrations, models
import django.db.models.deletion
import mln.models.static


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0028_alter_module_is_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleexecutioncost',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='click_outcome',
            field=mln.models.static.EnumField(mln.models.static.ModuleOutcome, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleexecutioncost',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='moduleexecutioncost',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='moduleexecutioncosts', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='moduleguestyield',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='moduleguestyields', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='moduleguestyield',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='modulemessage',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='modulemessages', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='modulemessage',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='moduleowneryield',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='moduleowneryields', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='moduleowneryield',
            name='probability',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
