# Generated by Django 4.2.5 on 2025-07-05 12:08

from django.db import migrations, models
import django.db.models.deletion
import mln.models.static.static


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0032_profile_is_secret_alter_messagebody_easy_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkerreply',
            name='trigger_item_obtained',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('type', mln.models.static.static.ItemType['BADGE']), ('type', mln.models.static.static.ItemType['BLUEPRINT']), ('type', mln.models.static.static.ItemType['ITEM']), ('type', mln.models.static.static.ItemType['MASTERPIECE']), ('type', mln.models.static.static.ItemType['MODULE']), ('type', mln.models.static.static.ItemType['MOVIE']), ('type', mln.models.static.static.ItemType['SKIN']), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='messagebody',
            name='easy_replies',
            field=models.ManyToManyField(blank=True, related_name='+', to='mln.messagebody'),
        ),
        migrations.AlterField(
            model_name='moduleexecutioncost',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='moduleguestyield',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='modulemessage',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='mln.iteminfo'),
        ),
        migrations.AlterField(
            model_name='moduleowneryield',
            name='module_item',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', mln.models.static.static.ItemType['MODULE'])), on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='mln.iteminfo'),
        ),
    ]
