# Generated by Django 4.2.5 on 2025-07-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0032_alter_messagebody_easy_replies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkerpagesource',
            name='networker',
        ),
        migrations.DeleteModel(
            name='NetworkerFriendshipConditionSource',
        ),
        migrations.DeleteModel(
            name='NetworkerPageSource',
        ),
    ]
