# Generated by Django 4.2.5 on 2025-07-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0034_robotchroniclesmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotchroniclesmessage',
            old_name='rank',
            new_name='award',
        ),
    ]
