# Generated by Django 4.2.5 on 2025-07-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0035_robotchroniclesmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_secret',
            field=models.BooleanField(default=False, help_text='If true, this user is a secret networker and should not be displayed in public friend lists.'),
        ),
    ]
