# Generated by Django 4.2.22 on 2025-07-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0037_networkerreply_trigger_item_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pseudo',
            field=models.BooleanField(default=False),
        ),
    ]
