# Generated by Django 4.2.22 on 2025-07-16 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mln', '0038_profile_is_pseudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.oauthclient')),
                ('networker', models.ForeignKey(limit_choices_to={'profile__is_networker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.messagetemplate')),
            ],
        ),
        migrations.RemoveField(
            model_name='robotchroniclesmessage',
            name='networker',
        ),
        migrations.RemoveField(
            model_name='robotchroniclesmessage',
            name='template',
        ),
        migrations.DeleteModel(
            name='CoastGuardMessage',
        ),
        migrations.DeleteModel(
            name='RobotChroniclesMessage',
        ),
    ]
