# Generated by Django 4.2.22 on 2025-07-23 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mln', '0038_profile_is_pseudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='robotchroniclesmessage',
            name='networker',
        ),
        migrations.RemoveField(
            model_name='robotchroniclesmessage',
            name='template',
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='redirect_url',
            field=models.URLField(default='localhost:7000/api/login'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoastGuardMessage',
        ),
        migrations.DeleteModel(
            name='RobotChroniclesMessage',
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.oauthclient'),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='networker',
            field=models.ForeignKey(limit_choices_to={'profile__is_networker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.messagetemplate'),
        ),
    ]
