# Generated by Django 4.2.22 on 2025-07-17 09:00

from django.db import migrations, models
import django.db.models.deletion
import mln.models.dynamic.dynamic
import mln.models.static.static


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0039_integrationmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('type', mln.models.static.static.EnumField(mln.models.dynamic.dynamic.WebhookType)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.oauthclient')),
            ],
        ),
    ]
