# Generated by Django 4.2.22 on 2025-09-05 09:05

from django.db import migrations
import mln.models.static.static

class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0040_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebody',
            name='theme',
            field=mln.models.static.static.EnumField(mln.models.static.static.MessageBodyTheme, blank=True, null=True),
        ),
    ]
