# Generated by Django 4.2.22 on 2025-09-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mln', '0042_alter_webhook_access_token_alter_webhook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='auth_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mln.oauthcode'),
        ),
    ]
